### ISSUE TITLE
`erpione communication reply` requires `--actor` id and then fails

### ISSUE THREAD

**Issue by alisianoi** [gematik/erp-e2e-testsuite#6]
It looks like starting with `erpione` version `0.4.0` and above the `communication reply` subcommand now requires an explicit `--actor` identifier:

```
gematik•~» erpione --version                                                                                                                                                         [12:54:01]
erpione 0.4.2
gematik•~» erpione communication reply --taskid "160.000.226.542.978.71" examples/communication_reply_payload_01.json                                                                [12:56:35]
2024-08-13 12:56:56,026 [__init__.pyc        ] ERROR: No actor given. Please provide an actor with --actor
Traceback (most recent call last):
  File "erpione.py", line 185, in <module>
  File "erpione/apps/communication_handling.py", line 48, in reply
  File "erpione/rest/__init__.py", line 16, in ensure_actor_given
NameError: name 'exit' is not defined
[905] Failed to execute script 'erpione' due to unhandled exception!
```

On the `ru` namespace I have chosen the following actor and have tried to use its identifier to send a communication reply:

```
gematik•~» erpione actors --env ru
{
  "id": "6a7f66bc2bb0f4cd76deaa260abbb484",
  "type": "Arzt",
  "name": "Adelheid Ulmenwald",
  "tid": "1-2-ARZTPRAXIS-BerndRosenstrauch01",
  "smcb": "80276001011699901102",
  "publicKey": "MFowFAYHKoZIzj0CAQYJKyQDAwIIAQEHA0IABGc0iasne1f/tcuTSw4CiRfxZ3LvLsQDuMmbqTO5CuOsXND+n8fVQ3zyzOv7imMbR7nqdiEFGAHtGNznbsLrU80="
}

gematik•~» erpione prescribe --env ru examples/out/X123456788_gkv_bundle_01.xml                                                                                                      [12:49:18]
2024-08-13 12:49:28,510 [prescription_generator.pyc] INFO : [1|1] create prescription examples/out/X123456788_gkv_bundle_01.xml
2024-08-13 12:49:29,598 [prescription_generator.pyc] INFO : Created Prescription with Task-ID 160.000.226.542.978.71 and AccessCode 51ceffeef6b5372b8f7eb9848b80bc3ea8b3c82aad331dbb9122128127dfd576

gematik•~» erpione communication reply --taskid "160.000.226.542.978.71" --actor "6a7f66bc2bb0f4cd76deaa260abbb484" examples/communication_reply_payload_01.json                     [12:52:57]
2024-08-13 12:53:04,632 [rest_client.pyc     ] ERROR: 403: unknown error:
{"type": "INTERNAL","message": "Forbidden"}
                                                                                                                                                         [12:53:04]
gematik•~» erpione communication reply --taskid "160.000.226.542.978.71" --actor "1-2-ARZTPRAXIS-BerndRosenstrauch01" examples/communication_reply_payload_01.json                   [12:53:29]
2024-08-13 12:53:45,364 [rest_client.pyc     ] ERROR: 403: unknown error:
{"type": "INTERNAL","message": "Forbidden"}

gematik•~» erpione communication reply --taskid "160.000.226.542.978.71" --actor "80276001011699901102" examples/communication_reply_payload_01.json                                 [12:53:45]
2024-08-13 12:54:01,671 [rest_client.pyc     ] ERROR: 403: unknown error:
{"type": "INTERNAL","message": "Forbidden"}
```

It looks like trying to use any of the possible actor identifiers (internal id, telematik id or smcb) doesn't work and results in the same error message. Am I doing something wrong? Am I perhaps missing a permission grant from the actor to the health record?

**Comment by alexanderkaiser** [comment]
Hi @alisianoi it looks like you are trying to use a doctor actor to send a reply message. Try using one of the pharmacy actors.

**Comment by alisianoi** [comment]
Hi @alexanderkaiser, unfrotunately I am observing the same behavior, here is my attempt:

```
gematik•~» erpione actors --env ru
{
  "id": "9d393b62c35805b9e516d8ca1ef23285",
  "type": "Apotheke",
  "name": "Christine Ulmendorfer",
  "tid": "3-01.2.2023001.16.103",
  "smcb": "80276001011699902303",
  "publicKey": "MFowFAYHKoZIzj0CAQYJKyQDAwIIAQEHA0IABBCREArh+D82RZJqBuWsGEcw4GJSY1m6pBG0q6MmhVkQN+sR/v5kzlHNzVYigWGs5gmbhh6tEUw+6dD+D8fk3tE="
}

gematik•~» erpf replace kvnr --file-type xml --to X123456788 examples/gkv_bundle_01.xml                                                                             [8:03:14]
08:05:54.384 INFO  d.g.t.e.c.c.r.KvnrReplacer - Replace KVNR to X123456788 in KbvErpBundle (gkv_bundle_01.xml)

gematik•~» erpione prescribe --env ru examples/out/X123456788_gkv_bundle_01.xml                                                                                     [8:05:54]
2024-08-19 08:06:19,263 [prescription_generator.pyc] INFO : create output directory /home/gematik/examples/out/out
2024-08-19 08:06:19,263 [prescription_generator.pyc] INFO : [1|1] create prescription examples/out/X123456788_gkv_bundle_01.xml
2024-08-19 08:06:50,176 [prescription_generator.pyc] INFO : Created Prescription with Task-ID 160.000.226.554.834.05 and AccessCode 4383873b4c2b03a8431efc6a88a4495669fcf09d388f591f93313450fb6f26ed
2024-08-19 08:06:50,176 [xlsx_transformer.pyc] INFO : Write summary to /home/gematik/examples/out/out/kthon_ru_20240819_080650.xlsx

gematik•~» erpione communication reply --taskid "160.000.226.554.834.05" --actor "9d393b62c35805b9e516d8ca1ef23285" examples/communication_reply_payload_01.json    [8:07:14]
2024-08-19 08:07:40,813 [rest_client.pyc     ] ERROR: 403: unknown error:
{"type": "INTERNAL","message": "Forbidden"}

gematik•~» erpione communication reply --taskid "160.000.226.554.834.05" --actor "3-01.2.2023001.16.103" examples/communication_reply_payload_01.json               [8:07:40]
2024-08-19 08:08:02,093 [rest_client.pyc     ] ERROR: 403: unknown error:
{"type": "INTERNAL","message": "Forbidden"}

gematik•~» erpione communication reply --taskid "160.000.226.554.834.05" --actor "80276001011699902303" examples/communication_reply_payload_01.json                [8:08:02]
2024-08-19 08:08:11,619 [rest_client.pyc     ] ERROR: 403: unknown error:
{"type": "INTERNAL","message": "Forbidden"}
```

**Comment by alexanderkaiser** [comment]
Hallo @alisianoi 

sorry for the late response, I was not able to treat this issue due to vacation.

I tried to reproduce the issue but was not able to:

```
erpione communication reply --env rudev -t 160.000.099.561.549.41 --actor 9d393b62c35805b9e516d8ca1ef23285 resources/communication_reply_payload_01.json
2024-09-05 14:10:45,669 [communication_handling.py] INFO : Send CommunicationReply to K220635158 with SupplyOption onPremise for Prescription 160.000.099.561.549.41
2024-09-05 14:10:45,669 [communication_handling.py] INFO : CommunicationReply Message:
{
  "version": 1,
  "supplyOptionsType": "onPremise",
  "info_text": "Die Abholung ist ab sofort vor Ort m\u00f6glich",
  "url": "https://www.adler-apotheke-berlin-tegel.de/",
  "pickUpCodeHR": "12345",
  "pickUpCodeDMC": "6a3acd69-a01d-4780-885e-ea970b6aacdb"
}
2024-09-05 14:10:53,927 [communication_handling.py] INFO : Sending CommunicationReply Response: <Response [201]>
```

Good news however, I found the issue: on the `communication reply` calls you are missing the environment (while on prescribe you explicitly define the RU). Therefore the `403` makes perfectly sense, as by default ERPione tries to communication to TU which is not allowed with your API-Key.

To prevent similar issues the chapter 2.5 within the user-manual (configuration of the default environment) might be helpful. 

Btw. the Parameter `--actor` usually takes the internal actor-id (so `9d393b62c35805b9e516d8ca1ef23285` for the Pharmacy "Christine Ulmendorfer" is the correct identifier). Alternatively you might also use the name directly (`--actor "Christine Ulmendorfer"`) 

I hope that helps and solves your issue

**Comment by alisianoi** [comment]
Hello @alexanderkaiser, thank you for spotting my error and guiding me through the process!

With your help I was able to successfully send a "communication reply" message with `erpione`

Closing the issue as "solved"
